source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '10.0'

def shared_pods
  pod 'Alamofire', '~> 4.4'
  pod 'Kingfisher', '~> 3.13'
  pod 'PureLayout'
  pod 'SwiftLint'
end

target 'WeatherLondon' do
    shared_pods
end

#target 'WeatherLondonMockedLocal' do
#    inherit! :search_paths
#    shared_pods
#end

target 'WeatherLondonTests' do
    inherit! :search_paths
    shared_pods
end
